name: Sync External File
permissions:
  contents: write
  pull-requests: write
on:
  schedule:
    - cron: '0 0 * * *
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download file
        run: curl -o ./list https://raw.githubusercontent.com/hydraponique/roscomvpn-geosite/refs/heads/master/data/category-geoblock-ru
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Commit and Push
        run: |
          git add target/path/filename.ext
          git diff --staged --quiet || (git commit -m "Update external file" && git push)
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b sync-update
          git push -u origin sync-update
          gh pr create --title "Sync external file" --body "Automated update" --base main || true
